# Generated by Django 2.2.16 on 2023-12-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='original_images/')),
                ('processed_image', models.ImageField(upload_to='processed_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
