# Generated by Django 2.2.16 on 2023-12-05 08:50

from django.db import migrations, models
import restapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='original_image',
            field=models.ImageField(upload_to=restapp.models.upload_original_path),
        ),
    ]
