# Generated by Django 2.2.16 on 2023-12-05 09:01

from django.db import migrations, models
import restapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_auto_20231205_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='processed_image',
            field=models.ImageField(upload_to=restapp.models.upload_processed_path),
        ),
    ]
